[[dotfiles]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim ."

[[session]]
name = "tmux config"
path = "~/"
startup_command = "nvim ~/.tmux.conf"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "open ."

[[session]]
name = "tmp"
path = "/tmp/"
startup_command = "open ."

[[session]]
name = "tappypop"
path = "~/.ssh"
startup_command = "ssh tappypop"
